services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=game-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=hive_game
      - POSTGRES_SYNCHRONIZE=true
    depends_on:
      - game-db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev

  game-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=hive_game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf
    volumes:
      - game_db_data:/var/lib/postgresql/data
    ports:
      - "4001:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - game-db

volumes:
  game_db_data:
